name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: Compile cv
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: sphinxdoc/sphinx-latexpdf:latest
          options: -v ${{ github.workspace }}:/docs
          run: latexmk -outdir=/docs -pdf /docs/cv.tex
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply latexpdf changes
